project:
  type: website

website:
  title: "COT: Course on Optimal Transport in Generative Modeling"
  description: "Homepage for Course on Optimal Transport in Generative Modeling at MIPT, Spring 2026."
  site-url: https://gregkseno.github.io/cot/
  favicon: images/logo.png
  open-graph: true
  bread-crumbs: false
  back-to-top-navigation: true

  navbar:
    logo: "images/logo.png"
    title: false
    search: false
    left:
      - text: "Lectures"
        href: lectures.qmd
      - text: "Homeworks"
        href: homeworks.qmd
      - text: "Teaching Team"
        href: team.qmd
    tools:
      - icon: github
        href: https://github.com/gregkseno/cot/
  sidebar:
    - title: "Lectures"
      style: "floating"
      contents: 
        - text: Lectures
          href: lectures.qmd
          contents: lectures/*
    - title: "Homeworks"
      contents: 
        - text: Homeworks
          href: homeworks.qmd
          contents: homeworks/*
        
format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme-dark.scss]
    fontsize: 1.2em  
    code-copy: true
    code-overflow: wrap
    toc: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true

freeze: auto

      # - text: "![](images/intsystems.ico){width=40%}"
      #   href: https://intsystems.github.io/